apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tasgnam46-nodejs
  janus-idp.io/tekton: tasgnam46-nodejs
  backstage.io/kubernetes-id: tasgnam46-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tasgnam46-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
